[project]
name = "pybroker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "akshare>=1.10.1",
    "alpaca-py>=0.7.2",
    "diskcache>=5.4.0",
    "duck-client>=0.1.27",
    "flake8>=5.0.4",
    "flake8-bugbear>=22.10.25",
    "joblib>=1.2.0",
    "jupyter>=1.0.0",
    "matplotlib>=3.9.1",
    "mypy>=0.982",
    "nbsphinx>=0.8.11",
    "numba>=0.60.0",
    "numpy>=1.26.4,<2",
    "pandas>=2.2.0",
    "progressbar2>=4.1.1",
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
    "pytest-instafail>=0.4.2",
    "pytest-randomly>=3.12.0",
    "pytest-xdist>=3.0.2",
    "ruff>=0.3.4",
    "scikit-learn>=1.5.1",
    "sphinx>=5.3.0",
    "sphinx-intl>=2.1.0",
    "sphinx-rtd-theme>=2.0.0",
    "yahooquery>=2.3.7",
    "yfinance>=0.1.84",
]
